# Generated by Django 4.2.7 on 2026-04-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='comments_post_id_8fd787_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user_id', 'post'], name='likes_user_id_c98b73_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_deleted'], name='posts_is_dele_76d2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_deleted', '-created_at'], name='posts_is_dele_3cc8cf_idx'),
        ),
    ]
