# Generated by Django 5.1.6 on 2026-04-17 04:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID của User từ Auth Service",
                        max_length=50,
                    ),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("image", "Tạo ảnh"),
                            ("avatar", "Tạo avatar"),
                            ("audio", "Âm thanh"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("media_url", models.URLField(max_length=500)),
                (
                    "aspect_ratio",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "resolution_config",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_generations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=50)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Tạo ảnh"),
                            ("avatar", "Tạo avatar"),
                            ("audio", "Âm thanh"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("media_url", models.URLField(max_length=500)),
                ("prompt", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "generation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai.aigeneration",
                    ),
                ),
            ],
            options={
                "db_table": "user_assets",
                "ordering": ["-created_at"],
            },
        ),
    ]
