# Generated by Django 5.1.6 on 2026-04-20 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room_id", models.CharField(db_index=True, max_length=100)),
                ("sender_id", models.UUIDField()),
                ("receiver_id", models.UUIDField()),
                ("text", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "message_type",
                    models.IntegerField(choices=[(0, "Text"), (1, "Image")], default=0),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserStatus",
            fields=[
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("is_online", models.BooleanField(default=False)),
                ("last_active", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_status",
            },
        ),
    ]
